spring.application.name=cafe-primavera

# Base de datos Neon
spring.datasource.url=jdbc:postgresql://ep-bold-tree-agevh3b8-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XdZIP7Je5Svx

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Puerto
server.port=8080

spring.jpa.properties.hibernate.globally_quoted_identifiers=false
spring.jpa.properties.hibernate.type.wrapper_array_handling=ALLOW
